function obj = export_MET(obj, dir_export_MET, flag, option, force)
% The MET format(s) exist for historical reasons to ingest Msection data
% into the Renderer database.
% flag = 0 means old style MET, 
% flag = 1 is the one with z and temca conf included
% flag = 2 like flag = 1, but using renderer ids
% option = 2  use dir_export_MET input as the full file name
% force = 0 means only valid tiles will be exported (state >=1)

% Note: flag options 0 and 1 will be deprecated soon.

%% prepare and export MET file needed for ERIC to constuct CATMAID files
if nargin<3, flag = 0;option = 0;end
if nargin<4, option = 0;end
if nargin<5, force = 0;end
    xmb = 0;
    ymb = 0;

if option ==2
    fn = dir_export_MET;
else
fn = [dir_export_MET 'X_A_' num2str(obj.z) '.txt'];
end

fid = fopen(fn,'w');
for tix = 1:numel(obj.tiles)
    if obj.tiles(tix).state>=1 || force          % only export those that are turned on
        
        if flag == 0        % old style
            fprintf(fid,'%d\t%d\t%.12f\t%.12f\t%.12f\t%.12f\t%.12f\t%.12f\t%d\t%d\t%d\t%s\n',...
                obj.tiles(tix).id, ...
                1, ...
                obj.tiles(tix).tform.T(1), ...
                obj.tiles(tix).tform.T(2), ...
                obj.tiles(tix).tform.T(3) - xmb, ...
                obj.tiles(tix).tform.T(4), ...
                obj.tiles(tix).tform.T(5), ...
                obj.tiles(tix).tform.T(6) - ymb, ...
                obj.tiles(tix).col, ...
                obj.tiles(tix).row, ...
                obj.tiles(tix).cam, ...
                obj.tiles(tix).path);
        elseif flag==1
            fprintf(fid,'%d\t%d\t%d\t%.12f\t%.12f\t%.12f\t%.12f\t%.12f\t%.12f\t%d\t%d\t%d\t%s\t%d\n',...
                obj.z,...
                obj.tiles(tix).id, ...
                1, ...
                obj.tiles(tix).tform.T(1), ...
                obj.tiles(tix).tform.T(2), ...
                obj.tiles(tix).tform.T(3) - xmb, ...
                obj.tiles(tix).tform.T(4), ...
                obj.tiles(tix).tform.T(5), ...
                obj.tiles(tix).tform.T(6) - ymb, ...
                obj.tiles(tix).col, ...
                obj.tiles(tix).row, ...
                obj.tiles(tix).cam, ...
                obj.tiles(tix).path,...
                obj.tiles(tix).temca_conf );
        elseif flag==2    % this is the one almost exclusively used
            fprintf(fid,'%d\t%s\t%d\t%.12f\t%.12f\t%.12f\t%.12f\t%.12f\t%.12f\t%d\t%d\t%d\t%s\t%d\n',...
                obj.tiles(tix).z,...
                obj.tiles(tix).renderer_id, ...
                1, ...
                obj.tiles(tix).tform.T(1), ...
                obj.tiles(tix).tform.T(2), ...
                obj.tiles(tix).tform.T(3) - xmb, ...
                obj.tiles(tix).tform.T(4), ...
                obj.tiles(tix).tform.T(5), ...
                obj.tiles(tix).tform.T(6) - ymb, ...
                obj.tiles(tix).col, ...
                obj.tiles(tix).row, ...
                obj.tiles(tix).cam, ...
                obj.tiles(tix).path,...
                obj.tiles(tix).temca_conf);
        end
    end
end
fclose(fid);

